// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtzf6gox7OPUuBJGzQRVOPmSL2COzWRF0',
    appId: '1:377057480159:web:aa40846aae170e8582c86a',
    messagingSenderId: '377057480159',
    projectId: 'nav-kigali',
    authDomain: 'nav-kigali.firebaseapp.com',
    storageBucket: 'nav-kigali.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGtG8GUaYS5VZYwOOnvqtLJGjZXbdgnnc',
    appId: '1:377057480159:android:fa081d8d32209d2682c86a',
    messagingSenderId: '377057480159',
    projectId: 'nav-kigali',
    storageBucket: 'nav-kigali.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCinnvQxNZnzdTXlIICH1dCCrMwQYdoRg',
    appId: '1:377057480159:ios:445c0ae0b0b9a5e682c86a',
    messagingSenderId: '377057480159',
    projectId: 'nav-kigali',
    storageBucket: 'nav-kigali.firebasestorage.app',
    iosBundleId: 'com.example.navKigali',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCinnvQxNZnzdTXlIICH1dCCrMwQYdoRg',
    appId: '1:377057480159:ios:445c0ae0b0b9a5e682c86a',
    messagingSenderId: '377057480159',
    projectId: 'nav-kigali',
    storageBucket: 'nav-kigali.firebasestorage.app',
    iosBundleId: 'com.example.navKigali',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtzf6gox7OPUuBJGzQRVOPmSL2COzWRF0',
    appId: '1:377057480159:web:0d268a0b78c1296482c86a',
    messagingSenderId: '377057480159',
    projectId: 'nav-kigali',
    authDomain: 'nav-kigali.firebaseapp.com',
    storageBucket: 'nav-kigali.firebasestorage.app',
  );
}
